name: Clone to 'fabric-root' branch
on: [push, pull_request]

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: assets/minecraft
